### PR TITLE
Elm 0.18

### LINKED ISSUE #41: Checklist for Elm 0.18
Unlike Elm 0.17, version 0.18 will not require an immediate plugin update as it doesn't break the overall syntactic structure, but there are a few things that would be nice to do:

- [ ] remove backtick syntax
- [ ] disallow primes in identifiers
- [ ] remove [..] List range syntax (was it ever supported by the plugin?)
- [ ] [proposed changes](https://groups.google.com/d/msg/elm-dev/mMUCvhPEJxQ/rgW9v_2WAgAJ) to the set of default imports

### PR DESCRIPTION
**Pull request by ianp**
Resolves #41 (as noted in that issue the range syntax wasn't supported anyway).

### CODE REVIEW

**Comment by durkiewicz** [comment]
I agree with @klazuka - please remove `build.gradle` file.

**Comment by durkiewicz** [comment]
If you remove pre-0.18 syntax then please remove list range as well (e.g. `[1..n]`)

**Comment by durkiewicz** [comment]
@ianp Please open new pull request when you change the code accordingly to the comments. I'm closing this one because I think I wouldn't receive an email notification when an existing pull request is altered.

**Comment by ianp** [comment]
Agreed, the `build.gradle` file shouldn't have been included. Doh!

**Pull request merged**
