### PR TITLE
Feature/elm make annotations

### PR DESCRIPTION
**Pull request by jlagerweij**
PR for issue #67 

This would execute elm-make on save

### CODE REVIEW

**Comment by durkiewicz** [comment]
Thank you for your work. I'm sorry that it took me so long, but finally found some time to have a look at it. 
When I tried using your functionality I got the following error:
screenshot from 2017-07-27 17-41-46
Stack trace:
```
java.lang.IllegalStateException: Unknown error. Elm-make exit with code: 127
	at org.elmlang.intellijplugin.elmmake.ElmMake.getVersion(ElmMake.java:55)
	at org.elmlang.intellijplugin.settings.ElmPluginSettingsPage.getVersion(ElmPluginSettingsPage.java:94)
	at org.elmlang.intellijplugin.settings.ElmPluginSettingsPage.updateVersion(ElmPluginSettingsPage.java:86)
	at org.elmlang.intellijplugin.settings.ElmPluginSettingsPage.validate(ElmPluginSettingsPage.java:82)
	at org.elmlang.intellijplugin.settings.ElmPluginSettingsPage.update(ElmPluginSettingsPage.java:73)
```
I'm affraid you need to write a separate markdown document that explains how to configure this tool. It would be better to link such document on the settings page (instead of linking the main page of the repository)

**Comment by jlagerweij** [comment]
I recreated your situation using VirtualBox, ubuntu and by using nvm. Intellij does not use have the nvm loaded, so it basically cannot find the node executable.
There needs to  be a fix so the correct node version will be used. I will also add some code so the actual error is displayed, not just the error code.

**Comment by durkiewicz** [comment]
Thanks for fixing the `elm-make` path issue. It was not only for nvm Node.js installation. I tried installing Node with `apt-get` and symptoms were identical. But it doesn't matter as `node` is recognized just fine after your changes.

Now I am able to enable the feature but I do not get any compilation annotations. The `elm-make` process is executed and your code can read the return code of 1 but it doesn't read the output of the process. I suspect that there must be some issue with the way that you extract the output from the process. I've added one comment inside the code that might be helpful for you.
 
Good luck!

**Comment by jlagerweij** [comment]
The elm-make process is fired after a file has changed on disk. This is either upon saving explicitly or implicit when the Intellij editor looses focus. It then annotates the file with errors and warnings. You can hover the errors and warnings to see the elm-make text on that line of code.

I was also searching for the comment you made inside the code, but fail to see the comment. This might be because I am not familiair enough with Github PR process, but could you guide me to your comment?

**Comment by kengorab** [comment]
Any update on this pull request? I think this would be a game changer for Elm development in IntelliJ/WebStorm.

**Comment by jlagerweij** [comment]
I am currently waiting on @durkiewicz to answer my question as I cannot reproduce his problem.

**Review by durkiewicz — CHANGES_REQUESTED** [review]

**Comment by durkiewicz** [comment]
@jlagerweij I'm sorry for that. I forgot to click "Submit review" button. My bad.

Anyway, the annotator does not annotate anything on my environment (Ubuntu). Btw. what environment do you use?

**Comment by jlagerweij** [comment]
I am using a Macbook, but have tried to reproduce your issue on a VirtualBox running Ubuntu. I will try to do that again in an effort to reproduce the issue.

**Comment by jlagerweij** [comment]
@durkiewicz I just downloaded a VirtualBox image from osboxes.org, installed NodeJS according to https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions, installed IntelliJ IDEA. Then installed elm using sudo npm install -g elm. This results in elm-make in the /usr/local/bin/elm-make location. The plugin picks this automatically up. Then I opened some elm project and changed an argument type of a function. Then save to disk and see annotations. I even tried running the elm-plugin project in Linux and then running de plugin in debug mode in another Idea session. 
Perhaps you can check on your end if the process.getErrorStream() show some info on what is going wrong?

**Comment by jlagerweij** [comment]
@durkiewicz It took some time, as I am quite busy lately, but I have added a way to inform the user when the Elm make cannot be performed. I was able to recreate your issue where the process exit code was 1 but no JSON lines where present in the stdout. There probably is some output in stderr, so that is now forwarded to the user. The user should be able to correct the situation.

**Comment by jlagerweij** [comment]
I decided to release my own plugin for the elm-make annotations functionality: https://plugins.jetbrains.com/plugin/10359-elm-external-tools

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.

**Pull request closed without merging**
